name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.9.4'
      - name: Prep Build
        run: |
          export MIX_ENV=test
          mix local.hex --force && mix local.rebar --force
          mix deps.get && mix compile --warnings-as-errors
      - name: Run Credo
        run: |
          export MIX_ENV=test
          mix credo
      - name: Enforce Proper Formatting
        run: |
          export MIX_ENV=test
          mix format --check-formatted --dry-run
      - name: Run Tests
        run: |
          export MIX_ENV=test
          mix test
